# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'

matrix:
  fast_finish: true

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry yarn

cache:
  - "%LOCALAPPDATA%\\Yarn"

test_script:
  - cmd: yarn test:ci

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: '{build}'
